landing-ai/vision-agent

vision_agent/lmm/lmm.py
vision_agent/tools/__init__.py
vision_agent/tools/prompts.py
vision_agent/tools/tools.py

This PR adds some basic tools such as classifiers, detectors and segmentors and functions to allow the LMMs (in this case we are just using LLMs) to build the tools for the user. The prompting is from EasyTool which builds an agent that determines the parameters for each tool based off of the user question and the documentation for each tool.

Adding basic tools

---

vision_agent/image_utils.py
vision_agent/lmm/lmm.py
vision_agent/tools/tools.py

1. Implement the Grounding DINO tool.
2. Update the public endpoint of llava to the latest

Implement the Grounding DINO tool

---

vision_agent/tools/tools.py

Add two new models as new tools.

Add two new models: CLIP and Grounded SAM

---

poetry.lock
pyproject.toml
vision_agent/agent/vision_agent.py

It's not easy to see what tasks are planned, their dependencies, and the tool and its params in the log.
This PR improves it.
pretty print the planned tasks:
```
INFO:vision_agent.agent.vision_agent:Planned tasks:
┍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┯━━━━━━┯━━━━━━━━┑
│ task                                                                                                                         │   id │ dep    │
┝━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━┿━━━━━━━━┥
│ Extract image frames from the video file '/Users/asia/Downloads/frames/baby_cam1_40s.MP4' by 'extract_frames_'               │    1 │ [-1]   │ …
```

Make it easier to visualize planned tasks in logs

---

README.md
vision_agent/llm/__init__.py
vision_agent/llm/llm.py
vision_agent/lmm/__init__.py
vision_agent/lmm/lmm.py

Used this documentation https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/chatgpt?pivots=programming-language-chat-completions&tabs=python-new
You can run vision agent using Azure OpenAI with the following code:
```python
import vision_agent as va
agent = va.agent.VisionAgent(
task_model=va.llm.AzureOpenAILLM()
answer_model=va.llm.AzureOpenAILLM(),
reflection_model=va.lmm.AzureOpenAILMM(),
)
```
Where the `reflection_model` is an LMM not an LLM. Make sure you have set your Azure OpenAI environment variables:
```
AZURE_OPENAI_API_KEY="..."
AZURE_OPENAI_ENDPOINT="..."
```

Add Azure OpenAI

---

vision_agent/agent/agent.py
vision_agent/agent/vision_agent.py
vision_agent/image_utils.py

1. Add a callback for reporting the chat progress of an agent
2. Small improvements to image_utils to make it more robust: handle RGBA and larger image

Support streaming chat logs of an agent

---

vision_agent/agent/vision_agent.py
vision_agent/tools/__init__.py
vision_agent/tools/tools.py

A tool to describe and caption images. Can be used for image to text use cases

Add image caption tool

---

vision_agent/agent/vision_agent.py
vision_agent/tools/tools.py

1. Add a new tool that determines if a bbox is contained within another bbox
2. Add a max column width to the tabulated log, it helps reading logs and understanding the agent logs.

Add a new tool: determine if a bbox is contained within another bbox

---

tests/test_tools.py
vision_agent/agent/vision_agent.py
vision_agent/image_utils.py

Report visualization images via callback.
This enables client apps to show those visualization images on a UI.
Images are sent via text in below format:
```
<VIZ>
<IMG>{base64 encoded image 1}</IMG>
<IMG>{base64 encoded image 2}</IMG>
<IMG>{base64 encoded image 3}</IMG>
</VIZ>
```
Minor tweaks:
1. change b64 encoding back to PNG
2. loosen some test assertion

feat(vision_agent): report visualization images via callback

---

vision_agent/agent/vision_agent.py

When the `_handle_viz_tools` looks for call results to extract info from it can be a dictionary with "bboxes", "masks" or "heat_map". I forgot to add back in "masks" in the last PR. It actually doesn't matter right now because all tools that return masks also return bboxes.

Add mask key for visualization

---

vision_agent/agent/__init__.py
vision_agent/agent/agent_coder.py
vision_agent/agent/agent_coder_prompts.py
vision_agent/agent/execution.py
vision_agent/agent/vision_agent.py
vision_agent/tools/tool_utils.py
vision_agent/tools/tools.py
vision_agent/tools/tools_v2.py

First PR for adding in AgentCoder. This is just an example of how to get an agent to code, but some of the abstractions here, like tools_v2, I want to use for other coding examples.
Typing issues: It looks like Windows doesn't support a lot of the resource or signal methods/constants, so I have a few `@typing.no_type_check`'s in there to ignore a lot of the typing issues. If you add too many `# type: ignore` then Linux/Mac will complain about unnecessary `# type: ignore`'s

AgentCoder-like Example for Coding Solutions

---

tests/test_llm.py
vision_agent/agent/vision_agent_v2.py
vision_agent/agent/vision_agent_v2_prompt.py
vision_agent/llm/llm.py
vision_agent/utils/__init__.py
vision_agent/utils/sim.py

Adding the remaining two items, long term memory and feedback, for the programming Vision Agent. Tried to make the vision agent more stateless. Calling `chat_with_workflow` returns a lot of stuff now so that the agent doesn't have to hold on to it as state:
`working_memory` is the trial and error reflections the model creates when debugging failed code. You can obtain this and use it as long term memory for future usage:
```python
output = agent.chat_with_workflow([{"role": "user", "content": "..."}])
wm = output["working_memory"]
wm.save("working_mem")
wm = va.utils.load_sim("working_mem")
new_ltm = va.utils.merge_sim(wm, ltm)
agent = va.agent.VisionAgentV2(long_term_memory=new_ltm)
```
If a subtask in the plan fails, it will return the partially completed code and plan early. You can …

Add Long Term Memory and Feedback

---

tests/test_llm.py
vision_agent/agent/vision_agent.py

The main regression is on planning as gpt-4o sometimes is very quick to plan and pick the right tool. 
Tried GPT4o on Reflection and found similar behavior 
So hard coding GPT-4-Turbo for all 3 models in old vision agent

Keep GPT4-Turbo for old vision agent

---

vision_agent/agent/agent_coder.py
vision_agent/agent/vision_agent_v2.py
vision_agent/agent/vision_agent_v2_prompt.py
vision_agent/tools/tools_v2.py
vision_agent/utils/sim.py

- Fixed bug on calculating success
- Added threshold to top k tool retrieval, removes noise from retrieving low sim tools
- Updated prompts, attempting to get the agent to not delete correct previous code
- Fixed some bugs with agent coder, added pretty code print to agent coder

Minor Improvements to performance

---

poetry.lock
pyproject.toml
vision_agent/utils/type_defs.py

Add ipykernel as a dependency.
A small error happened due to missing kernel:
```
Traceback (most recent call last):
File "/Users/asia/work/repos/vision-agent/vision-agent-benchmark/eval_va_v2.py", line 31, in <module>
pred = _eva_record(record["question"], record["image_path"])
File "/Users/asia/work/repos/vision-agent/vision-agent-benchmark/eval_va_v2.py", line 11, in _eva_record
return agent.chat_with_workflow(
File "/Users/asia/Library/Caches/pypoetry/virtualenvs/vision-agent-4R5Yp0-v-py3.10/lib/python3.10/site-packages/langsmith/run_helpers.py", line 565, in wrapper
raise e
File "/Users/asia/Library/Caches/pypoetry/virtualenvs/vision-agent-4R5Yp0-v-py3.10/lib/python3.10/site-packages/langsmith/run_helpers.py", line 560, in wrapper
function_result = run_container["context"].run(
File …
```

Bug fix: missing kernel python3

---

poetry.lock
pyproject.toml
tests/test_tools.py
vision_agent/tools/tools.py
vision_agent/tools/tools_v2.py
vision_agent/utils/image_utils.py
vision_agent/utils/type_defs.py

Adding
- zero shot counting
- visual prompt counting
- clip
- image question answering
- image captioning
re-did all test cases so that it uses tools_v2 functions

Adding more cv tools to coder agent

---

vision_agent/agent/vision_agent_v2.py

add log_progress_callback lambda in vision agent v2 to log progress and code back to rest api
Test:
Tested locally, checkout the response at: https://va.landing.ai/chat/qAGBMwE

feat: log pregress for vision agent v2

---

vision_agent/agent/agent.py
vision_agent/agent/agent_coder.py
vision_agent/agent/vision_agent.py
vision_agent/agent/vision_agent_v2.py
vision_agent/agent/vision_agent_v3.py

also adjust the logging data format
what looks like for V2:
https://github.com/landing-ai/vision-agent/assets/132986242/95eb4605-0d37-402c-8401-b843bfd769ad
V3:
https://github.com/landing-ai/vision-agent/assets/132986242/4728641e-a9a7-49eb-81e7-2a5eff155224

feat: add progress logging for v2 and v3

---

vision_agent/agent/vision_agent.py
vision_agent/tools/tools.py
vision_agent/utils/execute.py

Currently, `chat_with_workflow()` shares a global sandbox, which  causes concurrency issues: parallel `chat_with_workflow()` execution could convolute/mess up the python runtime.
This PR changes it to creating a dedicated sandbox per `chat_with_workflow()` call.
1. Better code sandbox lifecycle management;
2. Support image visualization (model predictions) locally;
3. Minor documentation updates;

Better code sandbox lifecycle management

---

tests/test_tools.py
vision_agent/tools/tools.py

Added a new mask distance calculation based on contours and polygon
- Tested on couple of use cases, no memory spikes
- Compared values to original implementation and the values are very close
- Attaching pool use case comparison against multiple frames. Left side of diff is original, Right side is new implementation
-

Optimize mask distance

---

vision_agent/agent/vision_agent.py
vision_agent/tools/tools.py

1. My previous PR (#114) doesn't fix the `import typing.*` error properly. This PR fixes it and improve the way we append default imports, make it easier to maintain.
2. Tweak docs to avoid code failure around load_image() 
3. Minor fix for lint errors

Fix missing typing module error and improve load_image()

---

poetry.lock
pyproject.toml
vision_agent/agent/vision_agent.py

1. Add back langsmith for better observability.
2. Small refactor: abstract out `debug_code` as a function so each `debug_code` call can be traced.
3. Bump e2b and e2b-code-interpreter to the latest version

Integrate langsmith for better observability

---

examples/mask_app/app.py
poetry.lock
vision_agent/agent/vision_agent_prompts.py
vision_agent/utils/execute.py

Minor changes to support benchmarking
1. Tweak the tester prompt to return the output in a testing function
2. Add a `get_main_result()` to `Execution` class
3. Update langsmith to the latest version

Minor changes to support benchmarking

---

vision_agent/tools/tool_utils.py

Support custom tool endpoint via two env vars:
1. `TOOL_ENDPOINT_URL`
2. `TOOL_ENDPOINT_AUTH`

Support custom tool endpoint

---

vision_agent/utils/execute.py
vision_agent/utils/sim.py

Minor fix and improvement
1. Fix the issue that str result is wrapped with single quotes by notebook.
2. Cache top_k() for better performance

Minor fix and improvement

---

vision_agent/agent/vision_agent.py

Fixes a few issues
- Remove outer retry loop
- Add more context for debugger
- Fix max retries on testing plans

Fix minor issues

---

vision_agent/agent/vision_agent.py

fix: add back some logging for ui

---

vision_agent/tools/tool_utils.py
vision_agent/utils/exceptions.py
vision_agent/utils/execute.py

Capture and save the model tool call trace in the notebook execution result.
Example captured result in json format:
```
>>> execution.results[0]["application/json"]
{
"endpoint_url": "https://api.staging.landing.ai/v1/agent/model/tools",
"type": "tool_call",
"request": {
"prompt": "resistor",
"image": "x9IBVpht2cTBCVeWJYkpX6udUS7cAsov+WUhoOh8i3xI....",
"tool": "open_vocab_detection",
"kwargs": {
"box_threshold": 0.1,
"iou_threshold": 0.1
},
"runtime_tag": "local_dev"
},
"response": {
"data": {
"bboxes": [....],
"labels": [
"resistor",
"resistor",
"resistor",
"resistor",
"resistor",
"resistor"
],
"scores": [
0.19836127758026123,
0.13876622915267944,
0.12910357117652893,
0.1203366070985794,
0.11757179349660873,
0.10860796272754669
],
"count": 6
}
},
"error": null
}
```

Capture model tool call trace in the notebook execution result

---

vision_agent/tools/tools.py

The video cannot be played in the browser because the video encoding should be X264.
Slack thread: https://landingai.slack.com/archives/C07896KN3L0/p1722553166203759
Verified locally that the video can be played now:
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207947616642871

fix: `save_video` encoding should be `X264`

---

vision_agent/agent/vision_agent_coder.py

1. remove the code execution result from logs for `pick_plan`, otherwise the logs would be too large
2. exchange the sequence of one log when the first try failed in `pick_plan`, otherwise the retry would always show "Code execution failed"
Tested against the e2b backend
The responseBody size is much smaller.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207985513691304

fix: remove the code execution result from logs in `pick_plan`

---

vision_agent/tools/tools.py

When doing a tasks such as license plate detection, detected areas will be cropped and then fed to OCR model, but OCR model occasionally crashes if the cropped region is too small or out of bounds of the image. This makes it so the model doesn't have to debug this issue.

minor fix for ocr

---

vision_agent/tools/__init__.py
vision_agent/tools/tool_utils.py
vision_agent/tools/tools.py

for code editor to use to popup tool definition

feat: add dict to map func name to func docstring

---

vision_agent/utils/execute.py

According to E2B team, they have fixed the connection issue. So we can revert back to the production template and use GHA to build the template.

feat: revert e2b template back to va-sandbox

---

tests/integ/test_tools.py
vision_agent/agent/vision_agent_coder.py
vision_agent/tools/__init__.py
vision_agent/tools/tools.py

- Rename florence OD and tool desc
- Add tracking labels to overlay_Seg_masks
- Dont print all plans if not in multiplan mode
https://github.com/user-attachments/assets/f3cf6800-0d12-4706-b0f0-b3392f6d0e60

Minor tool fixes for Florence OD and Overlay Seg masks for tracking

---

vision_agent/agent/vision_agent_coder.py
vision_agent/lmm/lmm.py
vision_agent/tools/tools.py

We used to always use the local media:
- encode it as base64 and talk with OpenAI
- upload it to the code interpreter before execution
This PR adds the support to directly use the media URL
1. [OpenAI](https://platform.openai.com/docs/guides/vision?lang=curl) supports both base64 and URL format of the image
2. Added the support to download from URL in the tool `load_image` and `extract_frames`. Although the `moviepy` can directly use the URL, but after testing, looks like download it first seems more stable.
3. During `write_plan`, we need to feed the LLM one frame of the video, we assume there is a same url that only differs in the suffix. (https://xxxxx.mp4 -> https://xxxxx.png)
Local run:
- image
- video

feat: use media url directly in both LMM and code sandbox

---

vision_agent/tools/tools.py

feat: only expose FUNCTION_TOOLS to tool info for user to select from UI 

---

vision_agent/tools/tool_utils.py

Some tools use the `files` param in the `send_inference_request`, which cannot be captured by the `ToolCallTrace`
```python
buffer_bytes = frames_to_bytes(frames)
files = [("video", buffer_bytes)]
payload = {
"prompts": [s.strip() for s in prompt.split(",")],
"function_name": "florence2_sam2_video_tracking",
}
data: Dict[str, Any] = send_inference_request(
payload, "florence2-sam2", files=files, v2=True
```
This PR adds the `files` in `ToolCallTrace`, which are the base64 encoded files, so we can capture the tool input files in downstream processing.

feat: add files to tool call trace

---

vision_agent/agent/vision_agent.py
vision_agent/agent/vision_agent_prompts.py
vision_agent/tools/meta_tools.py
vision_agent/tools/tools.py

- Improve prompts related to fine tuning usage
- Add ability to pass `test_multi_plan` and `customized_tool_names` from VisionAgent to VisionAgentCoder

Improve Orchestrator

---

vision_agent/agent/vision_agent.py

also for s3 images load and save to local first

feat: add callback to stream back message

---

vision_agent/utils/execute.py

see title
When running conversation, e2b needs the OPENAI_API_KEY to run `generate_vision_code`

feat: add OPENAI_API_KEY to e2b env

---

vision_agent/agent/vision_agent.py
vision_agent/tools/meta_tools.py
vision_agent/utils/execute.py

feat: support artifact name display

---

vision_agent/agent/vision_agent.py
vision_agent/tools/meta_tools.py

https://github.com/user-attachments/assets/c9e5094c-0a02-4f9a-aeec-74ea55a60a43

feat: when code edited by code executed directly

---

vision_agent/tools/tool_utils.py

`countgd_counting` and `countgd_example_based_counting` are using `send_task_inference_request` to call the model, which does not have `function_name` in the request payload. However, the UI needs this name to correctly show the tool calls trace.
This PR makes sure the `function_name` is in the tool_calls payload.
Local test:

fix: add `function_name` in tool_calls `payload` if it's missing

---

README.md
docs/index.md
tests/integ/test_tools.py
tests/unit/test_utils.py
vision_agent/agent/__init__.py
vision_agent/agent/agent_utils.py
vision_agent/agent/vision_agent.py
vision_agent/agent/vision_agent_coder.py
vision_agent/agent/vision_agent_coder_prompts.py
vision_agent/agent/vision_agent_prompts.py
vision_agent/lmm/__init__.py
vision_agent/lmm/lmm.py
vision_agent/tools/__init__.py
vision_agent/tools/meta_tools.py
vision_agent/tools/tools.py
vision_agent/tools/tools_types.py
vision_agent/utils/image_utils.py
vision_agent/utils/video.py

This PR adds several big items:
- Adds AnthropicVisionAgent and makes it the default VisionAgent as well as VisionAgentCoder
- Adds OpenAIVisionAgent and OpenAIVisionAgentCoder
- Enables VisionAgent to view media to quickly answer questions about media
- Adds fine_tune_id to owl_v2 and florence2_sam2_image, and changes meta_tools to handle fine_tune_ids for generic object detectors. This helps an issue where sometimes Claude 3.5 will prefer florence2_phrase_grounding because it can be fine tuned
- Fixes issue with VisionAgent prompt that causes Claude 3.5 to occasionally output incorrect JSON responses
- Passes the plan thoughts from planning to the coder, the plan thoughts now also include more information such as thresholds

Full Claude Sonnet 3.5 Support

---

vision_agent/utils/execute.py

The Artifact path needs to be in sync between local and remote.
For local artifact, we always use "WORKSPACE/home/user"
But for e2b, the default upload path is "/home/user", which is not in sync with the local path. This may cause `FileNotFound` errors:

fix: remote path default to WORKSPACE, keep in sync with local path

---

vision_agent/agent/vision_agent.py
vision_agent/tools/meta_tools.py

https://app.asana.com/0/1204554785675703/1208368248793227/f
https://app.asana.com/0/1204554785675703/1208337670563247/f
https://github.com/user-attachments/assets/089abce9-7cef-4659-b365-3824359cdaf4

feat: error handling for conversation agent

---

vision_agent/agent/vision_agent.py
vision_agent/tools/tools.py

https://app.asana.com/0/home/1205168511493761/1208337670563239

fix: add func name to florencev2 fine tune

---

vision_agent/tools/meta_tools.py

https://app.asana.com/0/1204554785675703/1208390283551010

fix: fine tune multiple times should edit original id

---

vision_agent/agent/vision_agent_coder_prompts.py

Several changes were added to this PR:
- Added examples to the coder agent, this is to ensure it properly handles the function arguments (want it to take in a media path instead of a numpy array)
- Moved instructions to last part of prompt, seems to improve performance to have instructions last
- Extra instructions to not make dummy variables or functions

Fix several issues with VisionAgentCoder using Claude-3.5

---

examples/chat/app.py
tests/unit/test_meta_tools.py
tests/unit/test_va.py
vision_agent/agent/vision_agent.py
vision_agent/agent/vision_agent_coder.py
vision_agent/agent/vision_agent_coder_prompts.py
vision_agent/agent/vision_agent_prompts.py
vision_agent/tools/meta_tools.py

Fixes several issues/bugs with VisionAgent:
- Fixes bug where if you pass a list of size > 2 to `edit_vision_code` it will crash because you've passed more than one user role message in a row
- Fixes bug where it would hallucinate when using `view_media_artifact`
- Fixes issue where it would try to call `view_media_artifact` on the users behalf
- Fixes issue where it could not write numpy arrays with `write_media_artifact`
- Adds rule for ensuring it will only call `edit_vision_code` on code generated from `generate_vision_code`, as opposed to using `edit_code_artifact`
- Adds rule for ensuring it will not continue to modify code for things the user did not ask for. For example, sometimes after generating vision code it would modify it to include visualizations
- Added more test cases for …

Fix for several issues with VisionAgent

---

vision_agent/tools/tools.py

when overlaying counting results visualizations, the label should not start at zero but at 1.

fix: labels should start at 1 instead of 0

---

vision_agent/tools/tools.py

if the API that the vision agent uses for a certain tool changes, the output schema needs to be exactly the same so that the UI can render the results. This PR reverts an API change for countgd in this PR: #253

fix: fix countgd api to match the UI

---

vision_agent/tools/tools.py

Description
---
* Update the Florence2Sam2 video `chunk_length` default value from `None` to `3`
* The original model uses as default a value of `20` for `chunk_length` which in some cases can be a very large default value for the subsampled videos.

chore: update fl2sm2 chunk_length default param

---

examples/chat/app.py
tests/unit/test_meta_tools.py
tests/unit/test_va.py
vision_agent/agent/vision_agent.py
vision_agent/tools/meta_tools.py

Fixes 2 issues:
- Bug with adding extra args to `edit_vision_code`, would add `test_multi_plan` but that arg doesn't exists
- Strips text after <execute_python> to mitigate hallucination issues

Fix Issues

---

examples/chat/app.py
vision_agent/agent/vision_agent.py

Reverts back to old format outside of vision agent

Fix issues 4

---

tests/integ/test_tools.py
tests/unit/test_vac.py
vision_agent/agent/vision_agent.py
vision_agent/tools/meta_tools.py

Moves the function to extract save files to after code has been executed by VisionAgent. Previously it was only looking at generated code, but now it looks at code and output in case something saves to a temporary file and you don't know the output until it's printed.

Fix Extract Files

---

vision_agent/agent/vision_agent.py

The generated code could be failed to parse and the error message were streaming back to UI, however, if that happened, the latest assistant response were not streamed because the while loop was break, so moved the code to stream back assistant response first before parse code action.
Confirmed with running examples in UI and make sure the UI behaves the same.

fix: streaming back assistant response before parse code action

---

poetry.lock
pyproject.toml
tests/unit/test_meta_tools.py
tests/unit/test_va.py
tests/unit/test_vac.py
vision_agent/agent/vision_agent_coder.py
vision_agent/tools/meta_tools.py

RedBaron is too old and runs in to a lot of issues, like it can't parse non-ascii characters. This replaces with libCST, a more modern and up to date python syntax tree parser.

Remove redbaron

---

tests/integ/test_tools.py
vision_agent/tools/__init__.py
vision_agent/tools/tools.py

Description
---
* Add qwen2vl-images vqa tool for answering questions on image documents.
* The function accepts list of images to answer questions to. The response is a single string.
Tests
---

chore: add qwen2vl-images vqa tool

---

tests/unit/tools/test_tools.py
vision_agent/tools/tools.py

fix: add empty check for bboxes in overlay_bounding_boxes
Problem:
We usually generate codes to directly pass bboxes returned from inference. If the inference happened to detect nothing, an empty list will be passed into `overlay_bounding_boxes`, which will raise an IndexError.
```python
image_with_boxes = overlay_bounding_boxes(image, car_detections)
output_path = image_path.rsplit('.', 1)[0] + '_with_cars.jpg'
save_image(image_with_boxes, output_path)
```
Solution:
Add empty array check inside `overlay_bounding_boxes`

fix: add empty check for bboxes in overlay_bounding_boxes

---

tests/integ/test_tools.py
vision_agent/tools/tools.py
vision_agent/tools/tools_types.py

- Use text-to-object-detection task API to run predictions for florence2, owlv2, countgd and any fine-tuned model (we can only run fine-tuned model with florence2).
- Add confidence param for owlv2 and countgd APIs. owlv2 will indeed utilize this param, countgd we still need to add this feature internally but I will already pass it from here so that is easier to remove the filter later on.
- Add the possibility to use a fine-tuned model with owlv2 video.

feat: use text-to-od on florence2 fine tuned, florence2, countgd and owlv2

---

tests/integ/test_tools.py
vision_agent/tools/__init__.py
vision_agent/tools/tools.py

Description
---
* Create the `qwen2_vl_video_vqa` tool for video analysis
* Add test for `qwen2_vl_video_vqa`
* Add the `qwen2_vl_images_vqa` and `qwen2_vl_video_vqa`
* Remove the `ixc25_image_vqa` and `ixc25_video_vqa` from the function tools list
Tests
---

chore: add qwen2vl model for image and video into function tools

---

vision_agent/tools/tools.py
vision_agent/utils/video.py

Better handle two edge cases in tools:
1. `fps` could be a str when it's passed in from a web deployment. So convert fps to float when it's a str.
2. Create the parent folder if it doesn't exist when saving file/image/video on disk.

Better handle two edge cases in tools

---

tests/unit/test_meta_tools.py
vision_agent/agent/vision_agent.py
vision_agent/agent/vision_agent_coder.py
vision_agent/agent/vision_agent_planner.py
vision_agent/tools/meta_tools.py

Currently we implement the `Artifact` based on the pickle.
This requires to load / save the files.
This PR changes the `Artifact` to be folder-based.
There is no need to load / save any more.
All the files under the `cwd` (current working directory) will be treated as the files inside the Artifact.
Also we want to keep the `chat_with_artifacts` running in the same environment with the code_interpreter. So we don't have to maintain "local" and "remote".
---
Local test
Code:
```python
from vision_agent.agent import VisionAgent
from vision_agent.tools.meta_tools import Artifacts
artifacts = Artifacts("/Users/zhichao/Projects/vision-agent-chat/va-local-test")
agent = VisionAgent(verbosity=1)
resp, artifacts = agent.chat_with_artifacts(
[
{
"role": "user",
"content": "Can you write code to …
```

feat: change the `Artifact` to be folder-based

---

vision_agent/tools/tool_utils.py

we will start tracking the runtime_tag on Snowflake data as a header, so this PR adds that as a header instead of the payload of the request.

fix: runtime_tag added as header instead of payload

---

README.md
docs/index.md
examples/chat/README.md
vision_agent/agent/vision_agent_coder.py
vision_agent/agent/vision_agent_planner.py
vision_agent/agent/vision_agent_planner_prompts.py
vision_agent/utils/sim.py

- Fixes an issue with OllamaSim that was causing it to crash.
- Updates Ollama model to `llama3.2-vision`
- Updates README, adds top level description on Ollama

Fix ollama issues

---

vision_agent/tools/tools.py

The response from owl_v2_video is the same as owl_v2_image (array of od annotations), but the expected response should be frames (array of array of od annotations).

fix: owl_v2_video tool response format

---

vision_agent/tools/tool_utils.py
vision_agent/tools/tools.py
vision_agent/utils/__init__.py

The `ipython.display.display` function is used to save data so it can be reported to our frontend web app.
As a side effect:
1.  The display function brings in non-trivial latency overhead when processing video files because it serializes video frames and prints them to stdout.
2. It floods the log making debugging harder.
`display()` is only useful in code generation time and when the frontend app is up. It's not used when users run the generated code offline.
Introduce a new env var `REPORT_TOOL_TRACES`, and VA only report traces when the env var is present.

only report tool traces in code generation time

---

tests/integ/test_tools.py
vision_agent/tools/__init__.py
vision_agent/tools/tools.py
vision_agent/utils/video_tracking.py

Description
---
* This PR introduces a new tool function to run fine-tuned object detection models

feat: add finetuned_object_detection tool

---

README.md
docs/index.md
tests/integ/test_tools.py
vision_agent/agent/types.py
vision_agent/agent/vision_agent_planner_v2.py
vision_agent/configs/anthropic_config.py
vision_agent/configs/openai_config.py
vision_agent/tools/__init__.py
vision_agent/tools/planner_tools.py
vision_agent/tools/tool_utils.py
vision_agent/tools/tools.py
vision_agent/utils/sim.py

- Adds update messages for planner
- Runs video tracking segments in parallel
- Filters double tool calls
- Fixes prompt case where tool tester doesn't have correct documentation to load media
- Fixes bug where code was not getting correctly extracted from debugger on tool testing
- Update temporal localization to output same length array as frames

Add Update Message & Filter Double Tool Calls

---

vision_agent/.sim_tools/df.csv
vision_agent/agent/agent_utils.py
vision_agent/agent/vision_agent_coder_prompts_v2.py
vision_agent/agent/vision_agent_coder_v2.py
vision_agent/agent/vision_agent_planner_prompts_v2.py
vision_agent/agent/vision_agent_planner_v2.py
vision_agent/agent/vision_agent_prompts_v2.py
vision_agent/agent/vision_agent_v2.py
vision_agent/tools/planner_tools.py
vision_agent/tools/tools.py

Several Updates:
- Updated coding prompt to return only final answer and not additional information
- If plan_context contains code, then coder will not write code, else coder will write code
- get_tool_for_task can take in dictionary of images to differentiate different images (helps with choosing flux as a tool)
- Update vision_agent_v2 prompt to not try to fix code on user's behalf
- Parallelizes temporal_localization
- Add inpainting and temporal localization to categorization request agent

Updates to Performance

---

vision_agent/tools/tools.py
vision_agent/utils/video.py

Fixes a permission issue on Windows in `frames_to_bytes`, it's caused when calling `with tempfile.NamedTemporaryFile(delete=True, ...)`, delete must be set to false, and then the file later deleted manually.
More info on this from the python docs https://docs.python.org/3/library/tempfile.html
Opening the temporary file again by its name while it is still open works as follows:
- On POSIX the file can always be opened again.
- On Windows, make sure that at least one of the following conditions are fulfilled:
- delete is false
- additional open shares delete access (e.g. by calling [os.open()](https://docs.python.org/3/library/os.html#os.open) with the flag O_TEMPORARY)
- delete is true but delete_on_close is false. Note, that in this case the additional opens that do not share delete …

Fix windows permission issue

---

.github/workflows/docs.yml

The version for `actions/upload-pages-artifacts` and `actions/deploy-pages` are out of date/deprecated. This updates the version https://github.com/actions/upload-pages-artifact

Fix docs github action

---

vision_agent/agent/vision_agent_planner_v2.py

The planner can generate images to view for debugging, but sometimes it can generate too many images which causes an error response from Anthropic. This puts a limit on how many images the planner can view.

limit images sent to planner

---

vision_agent/sim/sim.py
vision_agent/utils/tools.py

Tested locally and see MI has send inference history with vision_agent source

feat: add X-Source to inference request header

---

vision_agent/utils/tools.py

removes the use of an outdated environment variable for authorization when calling tools.

fix: remove outdated authorization
