landing-ai/vision-agent

.github/workflows/docs.yml, .gitignore, docs/_overrides/main.html, docs/api/agent.md, docs/api/data.md, docs/api/emb.md, docs/api/image_utils.md, docs/api/llm.md, docs/api/lmm.md, docs/api/tools.md, docs/index.md, docs/old.md, mkdocs.yml, vision_agent/agent/easytool.py, vision_agent/agent/reflexion.py, vision_agent/agent/vision_agent.py, vision_agent/image_utils.py, vision_agent/tools/tools.py
Changes
1. Automatically publish docs in CI;
2. Polish docs;
Notes:
1. Add or rename a module requires updating the docs under `docs/api`.
2. `docs/index.md` needs to be in-sync with `README.md` (as it is copied from it). Need to find a better way to avoid copying it.
3. Renamed the old doc, i.e. `docs/index.md` to docs/old.md`. We can later re-purpose it to a user guide.
=> Polish docs; Automatically publish docs in CI

README.md
I just adjusted the docs, where we would have an import of the VisionAgent.
=>  Little adjustment in the docs

.gitignore, vision_agent/tools/tools.py
The agent failed to pass the correct parameter name due to a name mismatch error.
Error Log:
```
┍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┯━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┑
│ task                                                                                                                                  │ tool_name   │ parameters                         │
┝━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━━━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┥
│ Use 'bbox_area_' to calculate the area of the bounding box of the coffee beans from the segmentation mask obtained in the second task …
```
=> Fix param name mismatch

README.md, vision_agent/agent/vision_agent.py
adding reflect to be optional for cases where LMM might not be able to understand the image
=> Enable/Disable Reflection

vision_agent/tools/tool_utils.py
Support identify internal calls via runtime tag
=> Support identify internal calls via runtime tag

poetry.lock, pyproject.toml, tests/fixtures.py, tests/test_llm.py, vision_agent/agent/vision_agent_v2.py, vision_agent/llm/llm.py
Integrate langsmith into `VisionAgentV2` for better observability
=> Integrate langsmith for better observability

vision_agent/tools/tool_utils.py, vision_agent/utils/type_defs.py
Switch to staging endpoint for better API availability
=> Switch to staging endpoint for better API availability

vision_agent/agent/agent_coder.py, vision_agent/agent/vision_agent.py, vision_agent/agent/vision_agent_prompts.py
- Change testing prompt to make sure there is no exception handling in test cases
- Allow user to use LMM for planning in AgentCoder and CoderV3
=> V3 improvments set2

vision_agent/agent/vision_agent.py
=> feat: log more tools info back to client

vision_agent/tools/tools.py
=> fix tool desc

vision_agent/utils/execute.py
Retry again when TimeoutError happens.
=> Handle TimeoutError with retry

vision_agent/tools/tools.py
=> Handle both normalized and denormalized coords in overlay bbox

README.md, docs/api/llm.md, docs/api/lmm.md, docs/index.md, vision_agent/llm/llm.py, vision_agent/lmm/lmm.py, vision_agent/utils/__init__.py, vision_agent/utils/sim.py
- You can now use Azure OpenAI embeddings for tool recommendation so Vision Agent can be completely run on AzureOpenAI
- Updated LLM/LMMs to use latest GPT-4o for AzureOpenAI
=> Fix azure OpenAI Embeddings

README.md, vision_agent/agent/__init__.py, vision_agent/agent/vision_agent.py
Introduce AzureVisionAgent for the ease of use of Azure OpenAI + Vision Agent.
=> Introduce AzureVisionAgent

README.md, vision_agent/lmm/lmm.py, vision_agent/utils/sim.py
Introduce two more env vars that is required to make it work:
1. AZURE_OPENAI_CHAT_MODEL_DEPLOYMENT_NAME
2. AZURE_OPENAI_EMBEDDING_MODEL_DEPLOYMENT_NAME
=> Fix AzureVisionAgent

vision_agent/agent/vision_agent.py
Add some loggings to reproduce json decoding errors
=> Add logging to extract_json()

poetry.lock, pyproject.toml, vision_agent/agent/vision_agent.py, vision_agent/tools/__init__.py, vision_agent/tools/tools.py
Fixes 2 issues:
- Trying to save RGBA images as JPEG (just convert all images to RGB)
- Trying to load HEIC images
=> Fix Issues

vision_agent/tools/tool_utils.py
I forgot to remove dead code in my previous PR #149 .
=> Remove dead code

vision_agent/agent/vision_agent.py
values() return dict_values type and is not json serializable, so need to convert to list
Tested locally and see success result:
=> fix: dict_values need to cast to list before json serialization

vision_agent/tools/tool_utils.py, vision_agent/utils/type_defs.py
Switch the tool endpoint to the production endpoint
=> Switch to prod tool endpoint

vision_agent/agent/vision_agent_coder.py
same as https://github.com/landing-ai/vision-agent/pull/183/files
=> fix: Fix debugging log + remove final_code (try 2) 

vision_agent/tools/tools.py
Fixes bug where prompt is sent with extra space (which then causes labels to have extra spaces)
=> fixed issue with space

README.md, docs/index.md
fix typo in readme to change verbose
=> fix_typo_readme_verbose

vision_agent/utils/execute.py
=> feat: make logs json searializable

vision_agent/agent/vision_agent.py, vision_agent/tools/meta_tools.py, vision_agent/utils/execute.py
=> feat: change the display on artifacts

vision_agent/tools/meta_tools.py
=> feat: new artifact structure

vision_agent/tools/meta_tools.py
fix: use od fine tune tool add action edit
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/1204554785675703/1208386627661278
=> fix: use od fine tune tool add action edit

vision_agent/tools/meta_tools.py
image：
https://github.com/user-attachments/assets/04d6a8af-7429-4873-807f-644339a08f21
video：
https://github.com/user-attachments/assets/d149106f-0b5a-416e-81b4-92153b6c7ad2
=> feat: display media artifact creation for ui

vision_agent/agent/vision_agent.py
Send dictionary instead of JSON string
=> fix stream message for front end

README.md, docs/index.md, examples/chat/README.md, vision_agent/agent/vision_agent.py, vision_agent/tools/meta_tools.py
Cleaned up artifact documentation and argument names. Fixed some issues when running VisionAgent without passing an artifact as an argument.
=> Better Artifact Argument Names

tests/integ/test_tools.py, vision_agent/tools/__init__.py, vision_agent/tools/tools.py
Description
---
* Add the video temporal localization tool to vision-agent
* Add test
=> chore: add video-temporal-localization

vision_agent/agent/vision_agent.py
There is one step on transforming code action before streaming response which is not used at all and could be removed:
checked locally and see complete result:
=> fix: remove extra step that could prevent response streaming back

tests/integ/test_tools.py, vision_agent/tools/tools.py
- Call text-to-seg API to process florence2-sam2 tasks.
- Add the possibility to fine-tune florence2sam2 using video.
=> feat: use text-to-seg on florence2sam2

tests/integ/test_tools.py, vision_agent/tools/tools.py
Description
---
* Add the video-temporal-localization tools to the function-tools list
* The benchmarking results show that the video-temporal-localization tool with the improved function description does not degrade the benchmark results (it even seems to improve the `video` category results) see the image below
=> chore: add video temporal localization tool

vision_agent/tools/tools.py
when there is no masks, the code errors out due to "index out of range".
exception trace:
```
File \"/home/appuser/.local/lib/python3.12/site-packages/starlette/middleware/errors.py\", line 165, in __call__
await self.app(scope, receive, _send)
File \"/home/appuser/.local/lib/python3.12/site-packages/starlette/middleware/base.py\", line 185, in __call__
with collapse_excgroups():
^^^^^^^^^^^^^^^^^^^^
File \"/usr/local/lib/python3.12/contextlib.py\", line 158, in __exit__
self.gen.throw(value)
File \"/home/appuser/.local/lib/python3.12/site-packages/starlette/_utils.py\", line 82, in collapse_excgroups
raise exc
File \"/home/appuser/.local/lib/python3.12/site-packages/starlette/middleware/base.py\", line 187, in __call__
response = await self.dispatch_func(request, call_next) …
```
=> fix 'list index out of range' in overlay_segmentation_masks

vision_agent/tools/tools.py
Description
---
Add the flux image tool into the `FUNCTION_TOOLS` list
=> chore: add flux image tool

tests/integ/test_tools.py, vision_agent/tools/tools.py
Update Flux1 to ensure big images are resized to max dimensions = (512, 512)
=> fix: update flux1 to ensure big images are resized

vision_agent/agent/vision_agent.py, vision_agent/tools/tools.py
- Remove redisplay for bounding boxes/segmentation masks
=> Minor Fixes

examples/chat/app.py, examples/chat/chat-app/src/components/ChatSection.tsx, vision_agent/agent/README.md, vision_agent/agent/agent.py, vision_agent/agent/types.py, vision_agent/agent/vision_agent_coder_v2.py, vision_agent/agent/vision_agent_planner_v2.py, vision_agent/agent/vision_agent_v2.py, vision_agent/tools/planner_tools.py, vision_agent/tools/tool_utils.py, vision_agent/utils/execute.py
This PR introduces human-in-the-loop interaction for V2 agents
=> Human-in-the-loop for V2 agents

vision_agent/agent/vision_agent_prompts.py
=> fix: edit_code_artifact param not same in prompt

vision_agent/tools/planner_tools.py
Lazy load the tool recommender (tool desc embeddings).
=> fix: do not require openai api key when importing VA lib

vision_agent/agent/vision_agent_coder_v2.py, vision_agent/tools/__init__.py, vision_agent/tools/planner_tools.py, vision_agent/tools/tools.py
abstract out get_tool_recommender() code into tools.py
=> refactor: abstract out get_tool_recommender() code into tools.py

tests/integ/test_tools.py, vision_agent/tools/__init__.py, vision_agent/tools/tools.py, vision_agent/utils/video_tracking.py
this pr adds the agentic object detection tools for: object detection, instance segmentation and video tracking. i manually ran the integration tests and they are all passing (see screenshot).
=> feat: add agentic od tools

vision_agent/agent/agent_utils.py, vision_agent/agent/vision_agent_coder_v2.py, vision_agent/agent/vision_agent_planner_prompts_v2.py, vision_agent/agent/vision_agent_v2.py
The conversation agent was not getting fed the correct information after running code which was leading to strange outputs
=> Fix bug in conversation agent

vision_agent/tools/tool_utils.py, vision_agent/tools/tools.py, vision_agent/utils/video_tracking.py
Fixes a couple issues with object tracking:
- Uses Hungarian matching for merging tracking segments
- Uses vectorized operations for changing masks to boxes in post processing
some stats on 10FPS ~17s clip:
- merge operation: 14.8s -> 12.9s
- post processing: 74.5s -> 9.8s
=> Update object tracking

vision_agent/tools/tools.py, vision_agent/utils/video.py
Better fix for this PR https://github.com/landing-ai/vision-agent/pull/362
=> Cleaner implementation for windows file issues

vision_agent/agent/vision_agent_prompts_v2.py
Giving the conversation agent, `VisionAgentV2`, more context so it can better address user concners.
=> VisionAgent Additional Context

vision_agent/agent/vision_agent_planner.py
Fixes this issue https://github.com/landing-ai/vision-agent/issues/373
=> fix ollama bug

vision_agent/agent/vision_agent_coder_v2.py, vision_agent/agent/vision_agent_planner_v2.py, vision_agent/tools/planner_tools.py, vision_agent/utils/agent.py
Addressing this issue https://github.com/landing-ai/vision-agent/issues/374 latest GPT-4o will sometimes ignore instructions and output markdown tags instead. This PR mitigates that issue
=> Fix parsing issues with new GPT

vision_agent/agent/README.md
=> docs: update agent/README.md

tests/integ/test_tools.py, vision_agent/sim/sim.py
this pr adds a runtime tag to the embeddings tool call and modifies some tests to make them run faster.
=> chore: add runtime_tag to stella embeddings

README.md, examples/chat/chat-app/src/components/VersionSelector.tsx, vision_agent/agent/vision_agent_v3.py
https://github.com/user-attachments/assets/752632b3-dda5-44f1-b27e-5cb4c97757ac
=> Add example
